Update image-trivyscanner.yml

diff --git a/.github/workflows/image-trivyscanner.yml b/.github/workflows/image-trivyscanner.yml
--- a/.github/workflows/image-trivyscanner.yml
+++ b/.github/workflows/image-trivyscanner.yml
@@ -1,32 +1,55 @@
-name: Trivy Vulnerability Scan
+name: Build, Push, and Scan Docker image
 
-on:  
+on:
   push:
     branches:
-      - main  # Run this workflow for pushes to the main branch
+      - main
+
+# Define the concurrency group
+concurrency: 
+  group: ghcr-build-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
-  trivy-scan:
-    runs-on: ubuntu-latest  
-
+  build-and-push:
+    runs-on: ubuntu-latest
     steps:
     - name: Check out the code
-      uses: actions/checkout@v2  
+      uses: actions/checkout@v2
 
-    - name: Set up Trivy
-      uses: aquasecurity/trivy-action@master
+    - name: Log in to GitHub Container Registry
+      uses: docker/login-action@v1
       with:
-        image-ref: 'ghcr.io/eziodevio/ghcr-democicdapp:v.1.2.1' # this is the image we built and pushed to GHCR
-        format: 'table'
-        exit-code: '1'
-        ignore-unfixed: true
-        severity: 'CRITICAL,HIGH'
-        output: 'trivy-results.txt'
-      # Trivy will scan the image and generate results
+        registry: ghcr.io
+        username: ${{ github.actor }}
+        password: ${{ secrets.GHCR_PAT }}
+
+    - name: Set lowercase repository owner
+      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')" >> $GITHUB_ENV
+
+    - name: Build Docker image with specific tag
+      run: |
+        echo "Image name: ghcr.io/${{ env.REPO_OWNER }}/ghcr-democicdapp:v.1.2.1"
+        docker build . -t ghcr.io/${{ env.REPO_OWNER }}/ghcr-democicdapp:v.1.2.1
+
+    - name: Push Docker image to GitHub Container Registry with tag v.1.2.1
+      run: docker push ghcr.io/${{ env.REPO_OWNER }}/ghcr-democicdapp:v.1.2.1
+
+    - name: Trivy Vulnerability Scan
+      run: |
+        set +e  # Prevent script from stopping on non-zero exit code
+        trivy image --severity HIGH,CRITICAL --format table --exit-code 1 --output trivy-results.txt ghcr.io/${{ env.REPO_OWNER }}/ghcr-democicdapp:v.1.2.1
+        scan_exit_code=$?
+        set -e  # Re-enable script stopping on non-zero exit code
+        if [ $scan_exit_code -ne 0 ]; then
+          echo "Trivy found vulnerabilities."
+          # Handle the vulnerability findings as needed
+        fi
+      continue-on-error: true  # This allows the job to continue even if this step fails
 
     - name: Upload Trivy scan results
+      if: always()  # Ensures that this step always runs, regardless of the previous step's outcome
       uses: actions/upload-artifact@v2
       with:
         name: trivy-results
         path: trivy-results.txt
-      # This step uploads the scan results as an artifact
